import { IconNames } from "./iconNames";
import type { Icon } from "./types";

// Import every icon SVG as a plain URL string (?url bypasses the image
// metadata pipeline, which rejects SVGs without intrinsic dimensions).
const svgs = import.meta.glob<string>("./content/icons/*.svg", {
  query: "?url",
  import: "default",
  eager: true,
});

const s = (file: string): string => {
  const url = svgs[`./content/icons/${file}.svg`];
  if (!url) throw new Error(`Missing icon SVG: ${file}.svg`);
  return url;
};

export const icons: Icon[] = [
  { name: IconNames.Angular, icon: s("angular") },
  { name: IconNames.Arduino, icon: s("arduino") },
  { name: IconNames.AWS, icon: s("aws") },
  { name: IconNames.Azure, icon: s("azure") },
  { name: IconNames.Bash, icon: s("bash") },
  { name: IconNames.CPP, icon: s("cpp") },
  { name: IconNames.Gatsby, icon: s("gatsby") },
  { name: IconNames.GoogleCloud, icon: s("gcloud") },
  { name: IconNames.Git, icon: s("git") },
  { name: IconNames.ApacheHadoop, icon: s("hadoop") },
  { name: IconNames.Java, icon: s("java") },
  { name: IconNames.Javascript, icon: s("javascript") },
  { name: IconNames.Kotlin, icon: s("kotlinlang") },
  { name: IconNames.Kubernetes, icon: s("kubernetes") },
  { name: IconNames.MongoDB, icon: s("mongodb") },
  { name: IconNames.MySQL, icon: s("mysql") },
  { name: IconNames.NodeJS, icon: s("nodejs") },
  { name: IconNames.Oracle, icon: s("oracle") },
  { name: IconNames.Python, icon: s("python") },
  { name: IconNames.Postgresql, icon: s("postgresql") },
  { name: IconNames.React, icon: s("react") },
  { name: IconNames.ApacheSpark, icon: s("spark") },
  { name: IconNames.SpringBoot, icon: s("spring") },
  { name: IconNames.TensorFlow, icon: s("tensorflow") },
  { name: IconNames.Typescript, icon: s("typescript") },
  { name: IconNames.Docker, icon: s("docker") },
  { name: IconNames.Ansible, icon: s("ansible") },
  { name: IconNames.Bootstrap, icon: s("bootstrap") },
  { name: IconNames.ApacheCassandra, icon: s("cassandra") },
  { name: IconNames.HTML, icon: s("html") },
  { name: IconNames.Jenkins, icon: s("jenkins") },
  { name: IconNames.ApacheKafka, icon: s("kafka") },
  { name: IconNames.Keras, icon: s("keras") },
  { name: IconNames.NeuralNetworks, icon: s("neuralnetwork") },
  { name: IconNames.CSS, icon: s("css") },
  { name: IconNames.GoLang, icon: s("golang") },
  { name: IconNames.GoGin, icon: s("gin") },
  { name: IconNames.NestJs, icon: s("nestjs") },
  { name: IconNames.GraphQL, icon: s("graphql") },
  { name: IconNames.Redis, icon: s("redis") },
  { name: IconNames.BitBucket, icon: s("bitbucket") },
  { name: IconNames.BlazeMeter, icon: s("blazemeter") },
  { name: IconNames.Confluence, icon: s("confluence") },
  { name: IconNames.Discord, icon: s("discord") },
  { name: IconNames.ElasticSearch, icon: s("elasticsearch") },
  { name: IconNames.Grafana, icon: s("grafana") },
  { name: IconNames.Idea, icon: s("idea") },
  { name: IconNames.Insomnia, icon: s("insomnia") },
  { name: IconNames.Jira, icon: s("jira") },
  { name: IconNames.Jmeter, icon: s("jmeter") },
  { name: IconNames.Kanban, icon: s("kanban") },
  { name: IconNames.Kibana, icon: s("kibana") },
  { name: IconNames.Postman, icon: s("postman") },
  { name: IconNames.Prometheus, icon: s("prometheus") },
  { name: IconNames.Pycharm, icon: s("pycharm") },
  { name: IconNames.Scrum, icon: s("scrum") },
  { name: IconNames.Agile, icon: s("scrum") },
  { name: IconNames.Splunk, icon: s("splunk") },
  { name: IconNames.VsCode, icon: s("vscode") },
  { name: IconNames.WaterFall, icon: s("waterfall") },
  { name: IconNames.WebStorm, icon: s("webstorm") },
  { name: IconNames.GoLand, icon: s("goland") },
  { name: IconNames.Slack, icon: s("slack") },
  { name: IconNames.Firebase, icon: s("firebase") },
  { name: IconNames.GithubActions, icon: s("githubactions") },
  { name: IconNames.PWA, icon: s("pwa") },
  { name: IconNames.Anthropic, icon: s("anthropic") },
  { name: IconNames.LangChain, icon: s("langchain") },
  { name: IconNames.HuggingFace, icon: s("huggingface") },
  { name: IconNames.Ollama, icon: s("ollama") },
  { name: IconNames.N8N, icon: s("n8n") },
  { name: IconNames.ComfyUI, icon: s("comfyui") },
].sort((a, b) => a.name.localeCompare(b.name));
